#!/bin/bash

webpage_input_dir="./input_webpages"
webpages_queue_dir="./script_data/webpages_queue"

# Load all the webpage entries from the webpages_input file to an array
webpages_input_array=()

while IFS= read -r input_url
do	
	# ${input_url:0:1} expands to the substring starting at position 
	# 0 of length 1 (gives us the first character of the line)
	if [ ${input_url:0:1} = "#" ]; then
		echo "Found # so line was discarded"
	else
		webpages_input_array+=("$input_url")
	fi
	
done < $webpage_input_dir

# Load all the webpage entries from the webpages_queue file to an array
webpages_queue_array=()

while IFS= read -r file_entry
do
	webpages_queue_array+=("$file_entry")
	
done < $webpages_queue_dir



# Iterate through all the webpage entries of the webpages_input_array,
# checking the webpages one by one

#echo "DEBUG --------------------"
#echo ${webpages_input_array[0]}
#echo ${webpages_input_array[1]}
#echo ${webpages_input_array[2]}
#echo "--------------------------"

for input_url in "${webpages_input_array[@]}"
do
	
	# Check whether the given url already exists in the webpages_queue_array
	found_url=0
	
	for queue_entry in "${webpages_queue_array[@]}"
	do
		# get the webpage url and the md5sum seperately
		entry_data=($queue_entry)
		queue_url=${entry_data[0]}
		url_md5sum=${entry_data[1]}
		
		if [ "$input_url" = "$queue_url" ]; then
			
			echo "Found the target url in the url_queue"
			found_url=1

			# *** Chech the webpage for changes ***
			# Download the currect webpage's md5sum and compare it 
			# to the stored md5sum for this webpage.
			current_md5sum=($(wget -q -O - $input_url | md5sum))

			if [ "$url_md5sum" != "$current_md5sum" ]; then
				# The webpage has changed
				echo "Detected changes in the given webpage"
				echo $queue_url
			fi
				
		fi
		
	done
	
	if [ $found_url = 0 ]; then
		echo "Target url was NOT found in the url_queue"

		# generate the webpage's md5sum
		url_md5sum=($(wget -q -O - $input_url | md5sum))

		# add the webpage's url and md5sum as a new entry to the webpages_queue_array
		webpages_queue_array+=("$input_url $url_md5sum")

		echo "$input_url INIT"
	fi
	
done

# Empty the webpages_queue file
> $webpages_queue_dir

# Save the current webpages_queue_array state to the webpages_queue file
for queue_entry in "${webpages_queue_array[@]}"
do
	#echo "mpika3-------------------"
	#echo $queue_entry
	#echo "-------------------------"
	echo $queue_entry >> $webpages_queue_dir
	#echo "" >> $webpages_queue_dir

done
















